apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "grafana.fullname" . }}
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: grafana
  template:
    metadata:
      labels:
        {{- include "grafana.labels" . | nindent 8 }}
        app.kubernetes.io/component: grafana
    spec:
      containers:
        - name: grafana
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          volumeMounts:
            - name: grafana-provisioning
              mountPath: /etc/grafana/provisioning/datasources/datasource.yml
              subPath: datasource.yml
            - name: grafana-provisioning
              mountPath: /etc/grafana/provisioning/dashboards/dashboard.yml
              subPath: dashboard.yml
            - name: grafana-dashboards
              mountPath: /etc/grafana/dashboards
            {{- if .Values.persistence.enabled }}
            - name: grafana-data
              mountPath: /var/lib/grafana
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: grafana-provisioning
          configMap:
            name: {{ include "grafana.fullname" . }}-provisioning
        - name: grafana-dashboards
          configMap:
            name: {{ include "grafana.fullname" . }}-dashboards
        {{- if .Values.persistence.enabled }}
        - name: grafana-data
          persistentVolumeClaim:
            claimName: {{ include "grafana.fullname" . }}
        {{- else }}
        - name: grafana-data
          emptyDir: {}
        {{- end }}
