apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090  # Correct Prometheus service inside Docker network
    isDefault: true
    jsonData:
      httpMethod: GET  # Explicitly set the HTTP method to GET
