{
 "title": "Styx Server Specific",
 "tags": [
  "Styx",
  "Server"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1s",
 "templating": {
  "list": [
   {
    "name": "Server",
    "query": {
     "query": "label_values(worker_epoch_latency_ms,exported_instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Utilization (%)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "worker_cpu_usage_percent{exported_instance=~\"$Server\"}"
    }
   ]
  },
  {
   "title": "Memory Utilization (Mb)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "worker_memory_usage_mb{exported_instance=~\"$Server\"} * 1000000"
    }
   ]
  },
  {
   "title": "Ingress Network (bytes/s)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "worker_network_rx_kb{exported_instance=~\"$Server\"} * 1000"
    }
   ]
  },
  {
   "title": "Egress Network (bytes/s)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "worker_network_tx_kb{exported_instance=~\"$Server\"} * 1000"
    }
   ]
  },
  {
   "title": "TPS (committed)",
   "type": "timeseries",
   "description": "Throughput per epoch of the committed transactions",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(worker_epoch_throughput_tps{exported_instance=~\"$Server\"})"
    }
   ]
  },
  {
   "title": "Transaction Latency",
   "type": "timeseries",
   "description": "Total latency of commited transactions",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(worker_epoch_latency_ms{exported_instance=~\"$Server\"})"
    }
   ]
  },
  {
   "title": "Abort Rate (%)",
   "type": "timeseries",
   "description": "Percentage of aborted transactions",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(worker_abort_percent{exported_instance=~\"$Server\"})"
    }
   ]
  },
  {
   "title": "Latency Breakdown",
   "type": "piechart",
   "description": "A breakdown of the transaction latency by component.",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "latency_breakdown{exported_instance=~\"$Server\"}",
     "legendFormat": "{{component}}"
    }
   ]
  },
  {
   "title": "Snapshot Latency",
   "type": "timeseries",
   "description": "Total latency for taking a snapshot",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(worker_total_snapshotting_time_ms{exported_instance=~\"$Server\"})"
    }
   ]
  }
 ]
}