apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "prometheus.fullname" . }}-config
  labels:
    {{- include "prometheus.labels" . | nindent 4 }}
data:
  prometheus.yml: |-
    global:
      scrape_interval: {{ .Values.scrapeInterval }}

    scrape_configs:
      - job_name: "styx"
        static_configs:
          - targets:
{{- $targets := .Values.scrapeTargets -}}
{{- if not $targets }}
{{- $targets = list (printf "%s-styx-coordinator:8000" .Release.Name) -}}
{{- end }}
{{- range $targets }}
            - {{ . | quote }}
{{- end }}
