global:
  security:
    allowInsecureImages: true

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

coordinator:
  image:
    repository: ghcr.io/delftdata/styx-coordinator
    tag: latest
    pullPolicy: Always
  replicas: 1
  ports:
    discovery: 8888
    protocol: 8889
    http: 8000
  env:
    HEARTBEAT_LIMIT: "5000"
    HEARTBEAT_CHECK_INTERVAL: "500"
  resources: {}
  service:
    type: ClusterIP

worker:
  replicas: 1
  image:
    repository: ghcr.io/delftdata/styx-worker
    tag: latest
    pullPolicy: Always
  env:
    INGRESS_TYPE: KAFKA
    WORKER_THREADS: "1"
  service:
    type: ClusterIP
    port: 8000

kafka:
  url: ""

rustfs:
  endpoint: ""
  accessKey: "rustfsadmin"
  secretKey: "rustfsadmin"
  bucket: "styx-snapshots"

monitoring:
  enabled: true
  metricsPath: /metrics

wait:
  enabled: true
  mode: k8s # tcp | k8s
  image:
    repository: "alpine/k8s"
    tag: "1.32.13"
    pullPolicy: IfNotPresent
  timeoutSec: 300
  sleepSec: 2
  waitForKafka: true
  waitForRustfs: true
  k8s:
    namespace: ""
    kafkaSelector: ""
    rustfsSelector: ""
