{{- $kafka := (.Values.kafka | default dict) -}}
{{- $coord := (.Values.coordinator | default dict) -}}
{{- $ports := ($coord.ports | default dict) -}}
{{- $mon := (.Values.monitoring | default dict) -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "styx.fullname" . }}-config
  labels:
    {{- include "styx.labels" . | nindent 4 }}
data:
  KAFKA_URL: {{ default (printf "%s-kafka-headless.%s.svc.cluster.local:9092" .Release.Name .Release.Namespace) $kafka.url | quote }}
  DISCOVERY_HOST: {{ printf "%s-coordinator" (include "styx.fullname" .) | quote }}
  DISCOVERY_PORT: {{ default 8888 $ports.discovery | quote }}
  METRICS_PATH: {{ default "/metrics" $mon.metricsPath | quote }}
