{{- $wait := (.Values.wait | default dict) -}}
{{- $waitMode := (default "tcp" $wait.mode) -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "styx.fullname" . }}
  labels:
    {{- include "styx.labels" . | nindent 4 }}
automountServiceAccountToken: {{ ternary true false (and (default false $wait.enabled) (eq $waitMode "k8s")) }}
